export const CAMPAIGN_SURVEY_REQUEST = "CAMPAIGN_SURVEY_REQUEST";
export const CAMPAIGN_SURVEY_SUCCESS = "CAMPAIGN_SURVEY_SUCCESS";
export const CAMPAIGN_SURVEY_FAIL = "CAMPAIGN_SURVEY_FAIL";
export const POST_CAMPAIGN_SURVEY_REQUEST = "POST_CAMPAIGN_SURVEY_REQUEST";
export const POST_CAMPAIGN_SURVEY_SUCCESS = "POST_CAMPAIGN_SURVEY_SUCCESS";
export const POST_CAMPAIGN_SURVEY_FAIL = "POST_CAMPAIGN_SURVEY_FAIL";
